-
  name: 'Node with format option'
  uriPattern: '{node}(.{@format})'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    'node':
      handler:     'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
  appendExceedingArguments: true

-
  name:          'Preview with format'
  uriPattern:    'neos/preview.{@format}'
  defaults:
    '@package' :   'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'preview'
  appendExceedingArguments: true
